name: Docker Image en Maven

on:
  push:
    branches:
      - maven  # Cambia esto por el nombre de tu rama principal si es diferente

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Azure Container Registry
        uses: docker/login-action@v1
        with:
          registry: gestionconfiguracion.azurecr.io 
          username: ${{ secrets.ACR_PUSH_USER }}
          password: ${{ secrets.ACR_PUSH_TOKEN }}

      - name: Generate version number
        id: version
        run: echo "::set-output name=version::$(($(date +%s)))"
        
      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .  
          push: true
          tags: ema/petclinic:${{ steps.version.outputs.version }}
