name: Build Linux Container Image and Push to ACR

on:
  push:
    branches: [ maven ]
  pull_request:
    branches: [ maven ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: dotnet
    steps:
    - uses: actions/checkout@v2
    - name: Generate version number
      id: version
      run: echo "::set-output name=version::${{ github.run_number }}"
    - uses: azure/docker-login@v1
      with:
        login-server: gestionconfiguracion.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build . gestionconfiguracion.azurecr.io/ema/petclinic:${{ steps.version.outputs.version }}
        docker push gestionconfiguracion.azurecr.io/ema/petclinic:${{ steps.version.outputs.version }}
